wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.9
    framework: huggingface
    huggingface_version: 4.46.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729819444
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 13
      - 23
      4: 3.11.9
      5: 0.17.9
      6: 4.46.0
      8:
      - 3
      - 5
      12: ''
      13: windows-amd64
